### PR TITLE
Added ability to select multiple images where supported.

### PR DESCRIPTION
**Pull request by ClumsySmurf**
Just added multi-pick intent stuff. Let me know if it isn't good, still a bit of an android noob.

### CODE REVIEW

**Comment by aviadmini** [comment]
Looks alright, I'll add something for multi-pick in next release

**Comment by ClumsySmurf** [comment]
I just added a null check for getClipData in PR. 

And Thanks for reviewing.

**Comment by aviadmini** [comment]
I looked up and seems that only `Intent.ACTION_GET_CONTENT` is able to make use of `Intent.EXTRA_PICK_MULTIPLE`. I guess I'll add an overload of `fromDocuments(boolean)` with allow multiple parameter. Also it's API 18 not 16

**Comment by aviadmini** [comment]
Closed with cb3865b, another chooser fix in d5ecccf

**Pull request closed without merging**
